<h3>earthygreen</h3>
<form id="example11-1">
	Check this box:
	<input type="checkbox" data-validate="required" />
	<input type="submit"/>
</form>

<h3>blackbubble</h3>
<form id="example11-2">
	Check this box:
	<input type="checkbox" data-validate="required" />
	<input type="submit"/>
</form>

<h3>mocha</h3>
<form id="example11-3">
	Check this box:
	<input type="checkbox" data-validate="required" />
	<input type="submit"/>
</form>

<h3>cutesy</h3>
<form id="example11-4">
	Check this box:
	<input type="checkbox" data-validate="required" />
	<input type="submit"/>
</form>