<form id="example8">
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<div><input type="text" value="hello world" data-validate="length(5)" /></div>
	<input type="submit" value="Submit" />
</form>