<form id="example2-1">
	<input type="text" id="field1" data-validate="required" value=""/>
	<input type="checkbox" id="field2" data-validate="required" value="1"/>
	<input type="submit" class="btn btn-primary" />
</form>

<form id="example2-2">
	<input type="text" id="field3" data-validate="required" value=""/>
	<input type="checkbox" id="field4" data-validate="required" value="1"/>
	<input type="submit" class="btn btn-primary" />
</form>