<form id="example9">
	<div><input type="text" value="" data-validate="required" /></div>
	<div><input type="text" value="" data-validate="required;alpha" /></div>
	<div><input type="text" value="" data-validate="required;email" /></div>
	<div><input type="text" value="" data-validate="required;numeric" /></div>
	<div><input type="text" value="" data-validate="required;length(3)" /></div>
	<div><input type="text" value="" data-validate="length(5)" /></div>
	<input type="submit" value="Submit" />
</form>