<form id="example17">
	<fieldset>
	<div class="row">
	<div class="span3">
		<label>Check this box</label>
		<input type="checkbox" data-validate="required" data-surrogate-element="#surrogate17" />
	</div>
	<div class="span3">
		<p id="surrogate17" style="border:2px solid #666;padding:18px;">feedback will point to this text</p>
	</div>
	</div>
	<input type="submit" value="Submit" />
	</fieldset>
</form>