<form id="example2-1">
	<table>
		<tr>
			<th>data-validate attribute</th>
			<th>Description</th>
			<th>Field</th>
		</tr>
		<tr>
			<td>required</td>
			<td></td>
			<td><input type="text" id="field1" data-validate="required" value="abc"/></td>
		</tr>
		<tr>
			<td>required</td>
			<td>must be checked</td>
			<td><input type="checkbox" id="field2" data-validate="required" value="1"/></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td><input type="submit"/></td>
		</tr>
		
	</table>
</form>

<form id="example2-2">
	<table>
		<tr>
			<th>data-validate attribute</th>
			<th>Description</th>
			<th>Field</th>
		</tr>
		<tr>
			<td>required</td>
			<td></td>
			<td><input type="text" id="field3" data-validate="required" value="abc"/></td>
		</tr>
		<tr>
			<td>required</td>
			<td>must be checked</td>
			<td><input type="checkbox" id="field4" data-validate="required" value="1"/></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td><input type="submit"/></td>
		</tr>
		
	</table>
</form>